// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public interface EnableMetricRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.EnableMetricRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.MonitorConfigId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.littlehorse.MonitorConfigId id = 1;</code>
   * @return The id.
   */
  io.littlehorse.sdk.common.proto.MonitorConfigId getId();
  /**
   * <code>.littlehorse.MonitorConfigId id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder getIdOrBuilder();

  /**
   * <code>int64 window_length_ms = 2;</code>
   * @return The windowLengthMs.
   */
  long getWindowLengthMs();
}
