// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public interface LatestMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.LatestMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.LatestMetricId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.littlehorse.LatestMetricId id = 1;</code>
   * @return The id.
   */
  io.littlehorse.sdk.common.proto.LatestMetricId getId();
  /**
   * <code>.littlehorse.LatestMetricId id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.LatestMetricIdOrBuilder getIdOrBuilder();

  /**
   * <code>int64 value = 2;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <code>.google.protobuf.Timestamp window_start = 3;</code>
   * @return Whether the windowStart field is set.
   */
  boolean hasWindowStart();
  /**
   * <code>.google.protobuf.Timestamp window_start = 3;</code>
   * @return The windowStart.
   */
  com.google.protobuf.Timestamp getWindowStart();
  /**
   * <code>.google.protobuf.Timestamp window_start = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp window_end = 4;</code>
   * @return Whether the windowEnd field is set.
   */
  boolean hasWindowEnd();
  /**
   * <code>.google.protobuf.Timestamp window_end = 4;</code>
   * @return The windowEnd.
   */
  com.google.protobuf.Timestamp getWindowEnd();
  /**
   * <code>.google.protobuf.Timestamp window_end = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder();
}
