// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

/**
 * Protobuf type {@code littlehorse.LHPartitionMonitor}
 */
public final class LHPartitionMonitor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:littlehorse.LHPartitionMonitor)
    LHPartitionMonitorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LHPartitionMonitor.newBuilder() to construct.
  private LHPartitionMonitor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LHPartitionMonitor() {
    tenantPartitions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LHPartitionMonitor();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHPartitionMonitor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHPartitionMonitor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.sdk.common.proto.LHPartitionMonitor.class, io.littlehorse.sdk.common.proto.LHPartitionMonitor.Builder.class);
  }

  public static final int TENANT_PARTITIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor> tenantPartitions_;
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor> getTenantPartitionsList() {
    return tenantPartitions_;
  }
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder> 
      getTenantPartitionsOrBuilderList() {
    return tenantPartitions_;
  }
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  @java.lang.Override
  public int getTenantPartitionsCount() {
    return tenantPartitions_.size();
  }
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor getTenantPartitions(int index) {
    return tenantPartitions_.get(index);
  }
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder getTenantPartitionsOrBuilder(
      int index) {
    return tenantPartitions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tenantPartitions_.size(); i++) {
      output.writeMessage(1, tenantPartitions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tenantPartitions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tenantPartitions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.sdk.common.proto.LHPartitionMonitor)) {
      return super.equals(obj);
    }
    io.littlehorse.sdk.common.proto.LHPartitionMonitor other = (io.littlehorse.sdk.common.proto.LHPartitionMonitor) obj;

    if (!getTenantPartitionsList()
        .equals(other.getTenantPartitionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTenantPartitionsCount() > 0) {
      hash = (37 * hash) + TENANT_PARTITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTenantPartitionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.sdk.common.proto.LHPartitionMonitor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code littlehorse.LHPartitionMonitor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.LHPartitionMonitor)
      io.littlehorse.sdk.common.proto.LHPartitionMonitorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHPartitionMonitor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHPartitionMonitor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.sdk.common.proto.LHPartitionMonitor.class, io.littlehorse.sdk.common.proto.LHPartitionMonitor.Builder.class);
    }

    // Construct using io.littlehorse.sdk.common.proto.LHPartitionMonitor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (tenantPartitionsBuilder_ == null) {
        tenantPartitions_ = java.util.Collections.emptyList();
      } else {
        tenantPartitions_ = null;
        tenantPartitionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHPartitionMonitor_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.LHPartitionMonitor getDefaultInstanceForType() {
      return io.littlehorse.sdk.common.proto.LHPartitionMonitor.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.LHPartitionMonitor build() {
      io.littlehorse.sdk.common.proto.LHPartitionMonitor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.LHPartitionMonitor buildPartial() {
      io.littlehorse.sdk.common.proto.LHPartitionMonitor result = new io.littlehorse.sdk.common.proto.LHPartitionMonitor(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.littlehorse.sdk.common.proto.LHPartitionMonitor result) {
      if (tenantPartitionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          tenantPartitions_ = java.util.Collections.unmodifiableList(tenantPartitions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tenantPartitions_ = tenantPartitions_;
      } else {
        result.tenantPartitions_ = tenantPartitionsBuilder_.build();
      }
    }

    private void buildPartial0(io.littlehorse.sdk.common.proto.LHPartitionMonitor result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.sdk.common.proto.LHPartitionMonitor) {
        return mergeFrom((io.littlehorse.sdk.common.proto.LHPartitionMonitor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.sdk.common.proto.LHPartitionMonitor other) {
      if (other == io.littlehorse.sdk.common.proto.LHPartitionMonitor.getDefaultInstance()) return this;
      if (tenantPartitionsBuilder_ == null) {
        if (!other.tenantPartitions_.isEmpty()) {
          if (tenantPartitions_.isEmpty()) {
            tenantPartitions_ = other.tenantPartitions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTenantPartitionsIsMutable();
            tenantPartitions_.addAll(other.tenantPartitions_);
          }
          onChanged();
        }
      } else {
        if (!other.tenantPartitions_.isEmpty()) {
          if (tenantPartitionsBuilder_.isEmpty()) {
            tenantPartitionsBuilder_.dispose();
            tenantPartitionsBuilder_ = null;
            tenantPartitions_ = other.tenantPartitions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tenantPartitionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTenantPartitionsFieldBuilder() : null;
          } else {
            tenantPartitionsBuilder_.addAllMessages(other.tenantPartitions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor m =
                  input.readMessage(
                      io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.parser(),
                      extensionRegistry);
              if (tenantPartitionsBuilder_ == null) {
                ensureTenantPartitionsIsMutable();
                tenantPartitions_.add(m);
              } else {
                tenantPartitionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor> tenantPartitions_ =
      java.util.Collections.emptyList();
    private void ensureTenantPartitionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tenantPartitions_ = new java.util.ArrayList<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor>(tenantPartitions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder> tenantPartitionsBuilder_;

    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public java.util.List<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor> getTenantPartitionsList() {
      if (tenantPartitionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tenantPartitions_);
      } else {
        return tenantPartitionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public int getTenantPartitionsCount() {
      if (tenantPartitionsBuilder_ == null) {
        return tenantPartitions_.size();
      } else {
        return tenantPartitionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor getTenantPartitions(int index) {
      if (tenantPartitionsBuilder_ == null) {
        return tenantPartitions_.get(index);
      } else {
        return tenantPartitionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder setTenantPartitions(
        int index, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor value) {
      if (tenantPartitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.set(index, value);
        onChanged();
      } else {
        tenantPartitionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder setTenantPartitions(
        int index, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder builderForValue) {
      if (tenantPartitionsBuilder_ == null) {
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.set(index, builderForValue.build());
        onChanged();
      } else {
        tenantPartitionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder addTenantPartitions(io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor value) {
      if (tenantPartitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.add(value);
        onChanged();
      } else {
        tenantPartitionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder addTenantPartitions(
        int index, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor value) {
      if (tenantPartitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.add(index, value);
        onChanged();
      } else {
        tenantPartitionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder addTenantPartitions(
        io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder builderForValue) {
      if (tenantPartitionsBuilder_ == null) {
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.add(builderForValue.build());
        onChanged();
      } else {
        tenantPartitionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder addTenantPartitions(
        int index, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder builderForValue) {
      if (tenantPartitionsBuilder_ == null) {
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.add(index, builderForValue.build());
        onChanged();
      } else {
        tenantPartitionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder addAllTenantPartitions(
        java.lang.Iterable<? extends io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor> values) {
      if (tenantPartitionsBuilder_ == null) {
        ensureTenantPartitionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tenantPartitions_);
        onChanged();
      } else {
        tenantPartitionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder clearTenantPartitions() {
      if (tenantPartitionsBuilder_ == null) {
        tenantPartitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tenantPartitionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public Builder removeTenantPartitions(int index) {
      if (tenantPartitionsBuilder_ == null) {
        ensureTenantPartitionsIsMutable();
        tenantPartitions_.remove(index);
        onChanged();
      } else {
        tenantPartitionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder getTenantPartitionsBuilder(
        int index) {
      return getTenantPartitionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder getTenantPartitionsOrBuilder(
        int index) {
      if (tenantPartitionsBuilder_ == null) {
        return tenantPartitions_.get(index);  } else {
        return tenantPartitionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public java.util.List<? extends io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder> 
         getTenantPartitionsOrBuilderList() {
      if (tenantPartitionsBuilder_ != null) {
        return tenantPartitionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tenantPartitions_);
      }
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder addTenantPartitionsBuilder() {
      return getTenantPartitionsFieldBuilder().addBuilder(
          io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.getDefaultInstance());
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder addTenantPartitionsBuilder(
        int index) {
      return getTenantPartitionsFieldBuilder().addBuilder(
          index, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.getDefaultInstance());
    }
    /**
     * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
     */
    public java.util.List<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder> 
         getTenantPartitionsBuilderList() {
      return getTenantPartitionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder> 
        getTenantPartitionsFieldBuilder() {
      if (tenantPartitionsBuilder_ == null) {
        tenantPartitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder>(
                tenantPartitions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        tenantPartitions_ = null;
      }
      return tenantPartitionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:littlehorse.LHPartitionMonitor)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.LHPartitionMonitor)
  private static final io.littlehorse.sdk.common.proto.LHPartitionMonitor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.sdk.common.proto.LHPartitionMonitor();
  }

  public static io.littlehorse.sdk.common.proto.LHPartitionMonitor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LHPartitionMonitor>
      PARSER = new com.google.protobuf.AbstractParser<LHPartitionMonitor>() {
    @java.lang.Override
    public LHPartitionMonitor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LHPartitionMonitor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LHPartitionMonitor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.sdk.common.proto.LHPartitionMonitor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

