// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public interface LHPartitionMonitorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.LHPartitionMonitor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  java.util.List<io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor> 
      getTenantPartitionsList();
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor getTenantPartitions(int index);
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  int getTenantPartitionsCount();
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  java.util.List<? extends io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder> 
      getTenantPartitionsOrBuilderList();
  /**
   * <code>repeated .littlehorse.LHTenantPartitionMonitor tenant_partitions = 1;</code>
   */
  io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder getTenantPartitionsOrBuilder(
      int index);
}
