// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public interface LHTenantPartitionMonitorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.LHTenantPartitionMonitor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
   * @return Whether the metricId field is set.
   */
  boolean hasMetricId();
  /**
   * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
   * @return The metricId.
   */
  io.littlehorse.sdk.common.proto.MonitorConfigId getMetricId();
  /**
   * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder getMetricIdOrBuilder();

  /**
   * <code>.littlehorse.UsageMetric metrics = 2;</code>
   * @return Whether the metrics field is set.
   */
  boolean hasMetrics();
  /**
   * <code>.littlehorse.UsageMetric metrics = 2;</code>
   * @return The metrics.
   */
  io.littlehorse.sdk.common.proto.UsageMetric getMetrics();
  /**
   * <code>.littlehorse.UsageMetric metrics = 2;</code>
   */
  io.littlehorse.sdk.common.proto.UsageMetricOrBuilder getMetricsOrBuilder();
}
