// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

/**
 * Protobuf type {@code littlehorse.LHTenantPartitionMonitor}
 */
public final class LHTenantPartitionMonitor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:littlehorse.LHTenantPartitionMonitor)
    LHTenantPartitionMonitorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LHTenantPartitionMonitor.newBuilder() to construct.
  private LHTenantPartitionMonitor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LHTenantPartitionMonitor() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LHTenantPartitionMonitor();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHTenantPartitionMonitor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHTenantPartitionMonitor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.class, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder.class);
  }

  public static final int METRIC_ID_FIELD_NUMBER = 1;
  private io.littlehorse.sdk.common.proto.MonitorConfigId metricId_;
  /**
   * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
   * @return Whether the metricId field is set.
   */
  @java.lang.Override
  public boolean hasMetricId() {
    return metricId_ != null;
  }
  /**
   * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
   * @return The metricId.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.MonitorConfigId getMetricId() {
    return metricId_ == null ? io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : metricId_;
  }
  /**
   * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder getMetricIdOrBuilder() {
    return metricId_ == null ? io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : metricId_;
  }

  public static final int METRICS_FIELD_NUMBER = 2;
  private io.littlehorse.sdk.common.proto.UsageMetric metrics_;
  /**
   * <code>.littlehorse.UsageMetric metrics = 2;</code>
   * @return Whether the metrics field is set.
   */
  @java.lang.Override
  public boolean hasMetrics() {
    return metrics_ != null;
  }
  /**
   * <code>.littlehorse.UsageMetric metrics = 2;</code>
   * @return The metrics.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.UsageMetric getMetrics() {
    return metrics_ == null ? io.littlehorse.sdk.common.proto.UsageMetric.getDefaultInstance() : metrics_;
  }
  /**
   * <code>.littlehorse.UsageMetric metrics = 2;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.UsageMetricOrBuilder getMetricsOrBuilder() {
    return metrics_ == null ? io.littlehorse.sdk.common.proto.UsageMetric.getDefaultInstance() : metrics_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metricId_ != null) {
      output.writeMessage(1, getMetricId());
    }
    if (metrics_ != null) {
      output.writeMessage(2, getMetrics());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metricId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetricId());
    }
    if (metrics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetrics());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor)) {
      return super.equals(obj);
    }
    io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor other = (io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor) obj;

    if (hasMetricId() != other.hasMetricId()) return false;
    if (hasMetricId()) {
      if (!getMetricId()
          .equals(other.getMetricId())) return false;
    }
    if (hasMetrics() != other.hasMetrics()) return false;
    if (hasMetrics()) {
      if (!getMetrics()
          .equals(other.getMetrics())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetricId()) {
      hash = (37 * hash) + METRIC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMetricId().hashCode();
    }
    if (hasMetrics()) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetrics().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code littlehorse.LHTenantPartitionMonitor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.LHTenantPartitionMonitor)
      io.littlehorse.sdk.common.proto.LHTenantPartitionMonitorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHTenantPartitionMonitor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHTenantPartitionMonitor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.class, io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.Builder.class);
    }

    // Construct using io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metricId_ = null;
      if (metricIdBuilder_ != null) {
        metricIdBuilder_.dispose();
        metricIdBuilder_ = null;
      }
      metrics_ = null;
      if (metricsBuilder_ != null) {
        metricsBuilder_.dispose();
        metricsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_LHTenantPartitionMonitor_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor getDefaultInstanceForType() {
      return io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor build() {
      io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor buildPartial() {
      io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor result = new io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metricId_ = metricIdBuilder_ == null
            ? metricId_
            : metricIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.metrics_ = metricsBuilder_ == null
            ? metrics_
            : metricsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor) {
        return mergeFrom((io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor other) {
      if (other == io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor.getDefaultInstance()) return this;
      if (other.hasMetricId()) {
        mergeMetricId(other.getMetricId());
      }
      if (other.hasMetrics()) {
        mergeMetrics(other.getMetrics());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMetricIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMetricsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.littlehorse.sdk.common.proto.MonitorConfigId metricId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.MonitorConfigId, io.littlehorse.sdk.common.proto.MonitorConfigId.Builder, io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder> metricIdBuilder_;
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     * @return Whether the metricId field is set.
     */
    public boolean hasMetricId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     * @return The metricId.
     */
    public io.littlehorse.sdk.common.proto.MonitorConfigId getMetricId() {
      if (metricIdBuilder_ == null) {
        return metricId_ == null ? io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : metricId_;
      } else {
        return metricIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    public Builder setMetricId(io.littlehorse.sdk.common.proto.MonitorConfigId value) {
      if (metricIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metricId_ = value;
      } else {
        metricIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    public Builder setMetricId(
        io.littlehorse.sdk.common.proto.MonitorConfigId.Builder builderForValue) {
      if (metricIdBuilder_ == null) {
        metricId_ = builderForValue.build();
      } else {
        metricIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    public Builder mergeMetricId(io.littlehorse.sdk.common.proto.MonitorConfigId value) {
      if (metricIdBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          metricId_ != null &&
          metricId_ != io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance()) {
          getMetricIdBuilder().mergeFrom(value);
        } else {
          metricId_ = value;
        }
      } else {
        metricIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    public Builder clearMetricId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metricId_ = null;
      if (metricIdBuilder_ != null) {
        metricIdBuilder_.dispose();
        metricIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.MonitorConfigId.Builder getMetricIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetricIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder getMetricIdOrBuilder() {
      if (metricIdBuilder_ != null) {
        return metricIdBuilder_.getMessageOrBuilder();
      } else {
        return metricId_ == null ?
            io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : metricId_;
      }
    }
    /**
     * <code>.littlehorse.MonitorConfigId metric_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.MonitorConfigId, io.littlehorse.sdk.common.proto.MonitorConfigId.Builder, io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder> 
        getMetricIdFieldBuilder() {
      if (metricIdBuilder_ == null) {
        metricIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.sdk.common.proto.MonitorConfigId, io.littlehorse.sdk.common.proto.MonitorConfigId.Builder, io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder>(
                getMetricId(),
                getParentForChildren(),
                isClean());
        metricId_ = null;
      }
      return metricIdBuilder_;
    }

    private io.littlehorse.sdk.common.proto.UsageMetric metrics_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.UsageMetric, io.littlehorse.sdk.common.proto.UsageMetric.Builder, io.littlehorse.sdk.common.proto.UsageMetricOrBuilder> metricsBuilder_;
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     * @return Whether the metrics field is set.
     */
    public boolean hasMetrics() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     * @return The metrics.
     */
    public io.littlehorse.sdk.common.proto.UsageMetric getMetrics() {
      if (metricsBuilder_ == null) {
        return metrics_ == null ? io.littlehorse.sdk.common.proto.UsageMetric.getDefaultInstance() : metrics_;
      } else {
        return metricsBuilder_.getMessage();
      }
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    public Builder setMetrics(io.littlehorse.sdk.common.proto.UsageMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metrics_ = value;
      } else {
        metricsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    public Builder setMetrics(
        io.littlehorse.sdk.common.proto.UsageMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        metrics_ = builderForValue.build();
      } else {
        metricsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    public Builder mergeMetrics(io.littlehorse.sdk.common.proto.UsageMetric value) {
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          metrics_ != null &&
          metrics_ != io.littlehorse.sdk.common.proto.UsageMetric.getDefaultInstance()) {
          getMetricsBuilder().mergeFrom(value);
        } else {
          metrics_ = value;
        }
      } else {
        metricsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    public Builder clearMetrics() {
      bitField0_ = (bitField0_ & ~0x00000002);
      metrics_ = null;
      if (metricsBuilder_ != null) {
        metricsBuilder_.dispose();
        metricsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    public io.littlehorse.sdk.common.proto.UsageMetric.Builder getMetricsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMetricsFieldBuilder().getBuilder();
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    public io.littlehorse.sdk.common.proto.UsageMetricOrBuilder getMetricsOrBuilder() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilder();
      } else {
        return metrics_ == null ?
            io.littlehorse.sdk.common.proto.UsageMetric.getDefaultInstance() : metrics_;
      }
    }
    /**
     * <code>.littlehorse.UsageMetric metrics = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.UsageMetric, io.littlehorse.sdk.common.proto.UsageMetric.Builder, io.littlehorse.sdk.common.proto.UsageMetricOrBuilder> 
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.sdk.common.proto.UsageMetric, io.littlehorse.sdk.common.proto.UsageMetric.Builder, io.littlehorse.sdk.common.proto.UsageMetricOrBuilder>(
                getMetrics(),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:littlehorse.LHTenantPartitionMonitor)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.LHTenantPartitionMonitor)
  private static final io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor();
  }

  public static io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LHTenantPartitionMonitor>
      PARSER = new com.google.protobuf.AbstractParser<LHTenantPartitionMonitor>() {
    @java.lang.Override
    public LHTenantPartitionMonitor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LHTenantPartitionMonitor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LHTenantPartitionMonitor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.sdk.common.proto.LHTenantPartitionMonitor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

