// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public final class Metrics {
  private Metrics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_MonitorConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_MonitorConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_MonitorConfigId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_MonitorConfigId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetrics.proto\022\013littlehorse\032\037google/pro" +
      "tobuf/timestamp.proto\032\017object_id.proto\"\205" +
      "\001\n\rMonitorConfig\022(\n\002id\030\001 \001(\0132\034.littlehor" +
      "se.MonitorConfigId\022\030\n\020window_length_ms\030\002" +
      " \001(\003\0220\n\014created_time\030\003 \001(\0132\032.google.prot" +
      "obuf.Timestamp\"\035\n\017MonitorConfigId\022\n\n\002id\030" +
      "\001 \001(\tBG\n\037io.littlehorse.sdk.common.proto" +
      "P\001Z\007.;model\252\002\030LittleHorse.Common.Protob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.littlehorse.sdk.common.proto.ObjectId.getDescriptor(),
        });
    internal_static_littlehorse_MonitorConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_littlehorse_MonitorConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_MonitorConfig_descriptor,
        new java.lang.String[] { "Id", "WindowLengthMs", "CreatedTime", });
    internal_static_littlehorse_MonitorConfigId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_littlehorse_MonitorConfigId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_MonitorConfigId_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.TimestampProto.getDescriptor();
    io.littlehorse.sdk.common.proto.ObjectId.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
