// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public final class Metrics {
  private Metrics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_MonitorConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_MonitorConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_MonitorConfigId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_MonitorConfigId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_EnableMetricRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_EnableMetricRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetrics.proto\022\013littlehorse\032\037google/pro" +
      "tobuf/timestamp.proto\"\205\001\n\rMonitorConfig\022" +
      "(\n\002id\030\001 \001(\0132\034.littlehorse.MonitorConfigI" +
      "d\022\030\n\020window_length_ms\030\002 \001(\003\0220\n\014created_t" +
      "ime\030\003 \001(\0132\032.google.protobuf.Timestamp\"\035\n" +
      "\017MonitorConfigId\022\n\n\002id\030\001 \001(\t\"Y\n\023EnableMe" +
      "tricRequest\022(\n\002id\030\001 \001(\0132\034.littlehorse.Mo" +
      "nitorConfigId\022\030\n\020window_length_ms\030\002 \001(\003B" +
      "G\n\037io.littlehorse.sdk.common.protoP\001Z\007.;" +
      "model\252\002\030LittleHorse.Common.Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_littlehorse_MonitorConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_littlehorse_MonitorConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_MonitorConfig_descriptor,
        new java.lang.String[] { "Id", "WindowLengthMs", "CreatedTime", });
    internal_static_littlehorse_MonitorConfigId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_littlehorse_MonitorConfigId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_MonitorConfigId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_EnableMetricRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_littlehorse_EnableMetricRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_EnableMetricRequest_descriptor,
        new java.lang.String[] { "Id", "WindowLengthMs", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
