// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public interface MonitorConfigIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.MonitorConfigId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.littlehorse.TenantId tenant_id = 2;</code>
   * @return Whether the tenantId field is set.
   */
  boolean hasTenantId();
  /**
   * <code>.littlehorse.TenantId tenant_id = 2;</code>
   * @return The tenantId.
   */
  io.littlehorse.sdk.common.proto.TenantId getTenantId();
  /**
   * <code>.littlehorse.TenantId tenant_id = 2;</code>
   */
  io.littlehorse.sdk.common.proto.TenantIdOrBuilder getTenantIdOrBuilder();
}
