// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

/**
 * Protobuf type {@code littlehorse.MonitorConfig}
 */
public final class MonitorConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:littlehorse.MonitorConfig)
    MonitorConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MonitorConfig.newBuilder() to construct.
  private MonitorConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MonitorConfig() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MonitorConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_MonitorConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_MonitorConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.sdk.common.proto.MonitorConfig.class, io.littlehorse.sdk.common.proto.MonitorConfig.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private io.littlehorse.sdk.common.proto.MonitorConfigId id_;
  /**
   * <code>.littlehorse.MonitorConfigId id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.littlehorse.MonitorConfigId id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.MonitorConfigId getId() {
    return id_ == null ? io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : id_;
  }
  /**
   * <code>.littlehorse.MonitorConfigId id = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder getIdOrBuilder() {
    return id_ == null ? io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : id_;
  }

  public static final int WINDOW_LENGTH_MS_FIELD_NUMBER = 2;
  private long windowLengthMs_ = 0L;
  /**
   * <code>int64 window_length_ms = 2;</code>
   * @return The windowLengthMs.
   */
  @java.lang.Override
  public long getWindowLengthMs() {
    return windowLengthMs_;
  }

  public static final int CREATED_TIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp createdTime_;
  /**
   * <code>.google.protobuf.Timestamp created_time = 3;</code>
   * @return Whether the createdTime field is set.
   */
  @java.lang.Override
  public boolean hasCreatedTime() {
    return createdTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_time = 3;</code>
   * @return The createdTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedTime() {
    return createdTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_time = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedTimeOrBuilder() {
    return createdTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (windowLengthMs_ != 0L) {
      output.writeInt64(2, windowLengthMs_);
    }
    if (createdTime_ != null) {
      output.writeMessage(3, getCreatedTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (windowLengthMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, windowLengthMs_);
    }
    if (createdTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCreatedTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.sdk.common.proto.MonitorConfig)) {
      return super.equals(obj);
    }
    io.littlehorse.sdk.common.proto.MonitorConfig other = (io.littlehorse.sdk.common.proto.MonitorConfig) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (getWindowLengthMs()
        != other.getWindowLengthMs()) return false;
    if (hasCreatedTime() != other.hasCreatedTime()) return false;
    if (hasCreatedTime()) {
      if (!getCreatedTime()
          .equals(other.getCreatedTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + WINDOW_LENGTH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWindowLengthMs());
    if (hasCreatedTime()) {
      hash = (37 * hash) + CREATED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.sdk.common.proto.MonitorConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.sdk.common.proto.MonitorConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.MonitorConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.sdk.common.proto.MonitorConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code littlehorse.MonitorConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.MonitorConfig)
      io.littlehorse.sdk.common.proto.MonitorConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_MonitorConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_MonitorConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.sdk.common.proto.MonitorConfig.class, io.littlehorse.sdk.common.proto.MonitorConfig.Builder.class);
    }

    // Construct using io.littlehorse.sdk.common.proto.MonitorConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      windowLengthMs_ = 0L;
      createdTime_ = null;
      if (createdTimeBuilder_ != null) {
        createdTimeBuilder_.dispose();
        createdTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.sdk.common.proto.Metrics.internal_static_littlehorse_MonitorConfig_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.MonitorConfig getDefaultInstanceForType() {
      return io.littlehorse.sdk.common.proto.MonitorConfig.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.MonitorConfig build() {
      io.littlehorse.sdk.common.proto.MonitorConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.MonitorConfig buildPartial() {
      io.littlehorse.sdk.common.proto.MonitorConfig result = new io.littlehorse.sdk.common.proto.MonitorConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.littlehorse.sdk.common.proto.MonitorConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.windowLengthMs_ = windowLengthMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.createdTime_ = createdTimeBuilder_ == null
            ? createdTime_
            : createdTimeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.sdk.common.proto.MonitorConfig) {
        return mergeFrom((io.littlehorse.sdk.common.proto.MonitorConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.sdk.common.proto.MonitorConfig other) {
      if (other == io.littlehorse.sdk.common.proto.MonitorConfig.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.getWindowLengthMs() != 0L) {
        setWindowLengthMs(other.getWindowLengthMs());
      }
      if (other.hasCreatedTime()) {
        mergeCreatedTime(other.getCreatedTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              windowLengthMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getCreatedTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.littlehorse.sdk.common.proto.MonitorConfigId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.MonitorConfigId, io.littlehorse.sdk.common.proto.MonitorConfigId.Builder, io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder> idBuilder_;
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     * @return The id.
     */
    public io.littlehorse.sdk.common.proto.MonitorConfigId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    public Builder setId(io.littlehorse.sdk.common.proto.MonitorConfigId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    public Builder setId(
        io.littlehorse.sdk.common.proto.MonitorConfigId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    public Builder mergeId(io.littlehorse.sdk.common.proto.MonitorConfigId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          id_ != null &&
          id_ != io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.MonitorConfigId.Builder getIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            io.littlehorse.sdk.common.proto.MonitorConfigId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.littlehorse.MonitorConfigId id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.MonitorConfigId, io.littlehorse.sdk.common.proto.MonitorConfigId.Builder, io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.sdk.common.proto.MonitorConfigId, io.littlehorse.sdk.common.proto.MonitorConfigId.Builder, io.littlehorse.sdk.common.proto.MonitorConfigIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private long windowLengthMs_ ;
    /**
     * <code>int64 window_length_ms = 2;</code>
     * @return The windowLengthMs.
     */
    @java.lang.Override
    public long getWindowLengthMs() {
      return windowLengthMs_;
    }
    /**
     * <code>int64 window_length_ms = 2;</code>
     * @param value The windowLengthMs to set.
     * @return This builder for chaining.
     */
    public Builder setWindowLengthMs(long value) {

      windowLengthMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 window_length_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowLengthMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      windowLengthMs_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     * @return Whether the createdTime field is set.
     */
    public boolean hasCreatedTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     * @return The createdTime.
     */
    public com.google.protobuf.Timestamp getCreatedTime() {
      if (createdTimeBuilder_ == null) {
        return createdTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdTime_;
      } else {
        return createdTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    public Builder setCreatedTime(com.google.protobuf.Timestamp value) {
      if (createdTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdTime_ = value;
      } else {
        createdTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    public Builder setCreatedTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdTimeBuilder_ == null) {
        createdTime_ = builderForValue.build();
      } else {
        createdTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    public Builder mergeCreatedTime(com.google.protobuf.Timestamp value) {
      if (createdTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          createdTime_ != null &&
          createdTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedTimeBuilder().mergeFrom(value);
        } else {
          createdTime_ = value;
        }
      } else {
        createdTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    public Builder clearCreatedTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createdTime_ = null;
      if (createdTimeBuilder_ != null) {
        createdTimeBuilder_.dispose();
        createdTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedTimeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCreatedTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedTimeOrBuilder() {
      if (createdTimeBuilder_ != null) {
        return createdTimeBuilder_.getMessageOrBuilder();
      } else {
        return createdTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_time = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedTimeFieldBuilder() {
      if (createdTimeBuilder_ == null) {
        createdTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedTime(),
                getParentForChildren(),
                isClean());
        createdTime_ = null;
      }
      return createdTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:littlehorse.MonitorConfig)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.MonitorConfig)
  private static final io.littlehorse.sdk.common.proto.MonitorConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.sdk.common.proto.MonitorConfig();
  }

  public static io.littlehorse.sdk.common.proto.MonitorConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MonitorConfig>
      PARSER = new com.google.protobuf.AbstractParser<MonitorConfig>() {
    @java.lang.Override
    public MonitorConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MonitorConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MonitorConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.sdk.common.proto.MonitorConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

