// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.littlehorse.sdk.common.proto;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_GetLatestUserTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_GetLatestUserTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutWfSpecRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutWfSpecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutWfSpecRequest_ThreadSpecsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutWfSpecRequest_ThreadSpecsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutWorkflowEventDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutWorkflowEventDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutUserTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutUserTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutExternalEventDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutExternalEventDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PutExternalEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PutExternalEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteExternalEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteExternalEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteWfRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteWfRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteUserTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteUserTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteWfSpecRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteWfSpecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteExternalEventDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteExternalEventDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_RunWfRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_RunWfRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_RunWfRequest_VariablesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_RunWfRequest_VariablesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableMatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableMatch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_AwaitWorkflowEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_AwaitWorkflowEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchWfRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchWfRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfRunIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_WfRunIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchTaskRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchTaskRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskRunIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskRunIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchNodeRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchNodeRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_NodeRunIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_NodeRunIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchUserTaskRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchUserTaskRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskRunIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskRunIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchVariableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchVariableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskDefIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskDefIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchUserTaskDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchUserTaskDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskDefIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskDefIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchWfSpecRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchWfSpecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfSpecIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_WfSpecIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchExternalEventDefRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchExternalEventDefRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ExternalEventDefIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ExternalEventDefIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchTenantRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchTenantRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TenantIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TenantIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchExternalEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchExternalEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SearchExternalEventRequest_ByExtEvtDefNameAndStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SearchExternalEventRequest_ByExtEvtDefNameAndStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ExternalEventIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ExternalEventIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListNodeRunsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListNodeRunsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_NodeRunList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_NodeRunList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListVariablesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListVariablesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListExternalEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListExternalEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ExternalEventList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ExternalEventList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_RegisterTaskWorkerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_RegisterTaskWorkerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskWorkerHeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskWorkerHeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_RegisterTaskWorkerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_RegisterTaskWorkerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_LHHostInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_LHHostInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PollTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PollTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ScheduledTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ScheduledTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PollTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_PollTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ReportTaskRun_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ReportTaskRun_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_StopWfRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_StopWfRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ResumeWfRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ResumeWfRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskDefMetricsQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskDefMetricsQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListTaskMetricsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListTaskMetricsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListTaskMetricsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListTaskMetricsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfSpecMetricsQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_WfSpecMetricsQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListWfMetricsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListWfMetricsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListWfMetricsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListWfMetricsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskDefMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskDefMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfSpecMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_WfSpecMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListUserTaskRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListUserTaskRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskRunList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskRunList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ListTaskRunsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ListTaskRunsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskRunList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskRunList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_MigrateWfSpecRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_MigrateWfSpecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_GetLatestWfSpecRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_GetLatestWfSpecRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ServerVersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ServerVersionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\013littlehorse\032\037google/pro" +
      "tobuf/timestamp.proto\032\033google/protobuf/e" +
      "mpty.proto\032\023common_wfspec.proto\032\022common_" +
      "enums.proto\032\017object_id.proto\032\016variable.p" +
      "roto\032\024external_event.proto\032\014wf_run.proto" +
      "\032\016node_run.proto\032\016task_run.proto\032\020user_t" +
      "asks.proto\032\rwf_spec.proto\032\016task_def.prot" +
      "o\032\nacls.proto\032\024workflow_event.proto\032\rmet" +
      "rics.proto\"+\n\033GetLatestUserTaskDefReques" +
      "t\022\014\n\004name\030\001 \001(\t\"\323\003\n\020PutWfSpecRequest\022\014\n\004" +
      "name\030\001 \001(\t\022D\n\014thread_specs\030\005 \003(\0132..littl" +
      "ehorse.PutWfSpecRequest.ThreadSpecsEntry" +
      "\022\036\n\026entrypoint_thread_name\030\006 \001(\t\022C\n\020rete" +
      "ntion_policy\030\010 \001(\0132$.littlehorse.Workflo" +
      "wRetentionPolicyH\000\210\001\001\022F\n\016parent_wf_spec\030" +
      "\t \001(\0132).littlehorse.WfSpec.ParentWfSpecR" +
      "eferenceH\001\210\001\001\0227\n\017allowed_updates\030\n \001(\0162\036" +
      ".littlehorse.AllowedUpdateType\032K\n\020Thread" +
      "SpecsEntry\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027" +
      ".littlehorse.ThreadSpec:\0028\001B\023\n\021_retentio" +
      "n_policyB\021\n\017_parent_wf_specJ\004\010\002\020\003J\004\010\003\020\004J" +
      "\004\010\004\020\005\"O\n\021PutTaskDefRequest\022\014\n\004name\030\001 \001(\t" +
      "\022,\n\ninput_vars\030\002 \003(\0132\030.littlehorse.Varia" +
      "bleDef\"S\n\032PutWorkflowEventDefRequest\022\014\n\004" +
      "name\030\001 \001(\t\022\'\n\004type\030\002 \001(\0162\031.littlehorse.V" +
      "ariableType\"{\n\025PutUserTaskDefRequest\022\014\n\004" +
      "name\030\001 \001(\t\022*\n\006fields\030\002 \003(\0132\032.littlehorse" +
      ".UserTaskField\022\030\n\013description\030\003 \001(\tH\000\210\001\001" +
      "B\016\n\014_description\"o\n\032PutExternalEventDefR" +
      "equest\022\014\n\004name\030\001 \001(\t\022C\n\020retention_policy" +
      "\030\002 \001(\0132).littlehorse.ExternalEventRetent" +
      "ionPolicy\"\303\002\n\027PutExternalEventRequest\022\'\n" +
      "\twf_run_id\030\001 \001(\0132\024.littlehorse.WfRunId\022>" +
      "\n\025external_event_def_id\030\002 \001(\0132\037.littleho" +
      "rse.ExternalEventDefId\022\021\n\004guid\030\003 \001(\tH\000\210\001" +
      "\001\022+\n\007content\030\005 \001(\0132\032.littlehorse.Variabl" +
      "eValue\022\036\n\021thread_run_number\030\006 \001(\005H\001\210\001\001\022\036" +
      "\n\021node_run_position\030\007 \001(\005H\002\210\001\001B\007\n\005_guidB" +
      "\024\n\022_thread_run_numberB\024\n\022_node_run_posit" +
      "ionJ\004\010\004\020\005J\004\010\010\020\t\"F\n\032DeleteExternalEventRe" +
      "quest\022(\n\002id\030\001 \001(\0132\034.littlehorse.External" +
      "EventId\"6\n\022DeleteWfRunRequest\022 \n\002id\030\001 \001(" +
      "\0132\024.littlehorse.WfRunId\":\n\024DeleteTaskDef" +
      "Request\022\"\n\002id\030\001 \001(\0132\026.littlehorse.TaskDe" +
      "fId\"B\n\030DeleteUserTaskDefRequest\022&\n\002id\030\001 " +
      "\001(\0132\032.littlehorse.UserTaskDefId\"8\n\023Delet" +
      "eWfSpecRequest\022!\n\002id\030\001 \001(\0132\025.littlehorse" +
      ".WfSpecId\"L\n\035DeleteExternalEventDefReque" +
      "st\022+\n\002id\030\001 \001(\0132\037.littlehorse.ExternalEve" +
      "ntDefId\"\343\002\n\014RunWfRequest\022\024\n\014wf_spec_name" +
      "\030\001 \001(\t\022\032\n\rmajor_version\030\002 \001(\005H\000\210\001\001\022\025\n\010re" +
      "vision\030\003 \001(\005H\001\210\001\001\022;\n\tvariables\030\004 \003(\0132(.l" +
      "ittlehorse.RunWfRequest.VariablesEntry\022\017" +
      "\n\002id\030\005 \001(\tH\002\210\001\001\0223\n\020parent_wf_run_id\030\006 \001(" +
      "\0132\024.littlehorse.WfRunIdH\003\210\001\001\032L\n\016Variable" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.lit" +
      "tlehorse.VariableValue:\0028\001B\020\n\016_major_ver" +
      "sionB\013\n\t_revisionB\005\n\003_idB\023\n\021_parent_wf_r" +
      "un_id\"L\n\rVariableMatch\022\020\n\010var_name\030\001 \001(\t" +
      "\022)\n\005value\030\002 \001(\0132\032.littlehorse.VariableVa" +
      "lue\"\275\001\n\031AwaitWorkflowEventRequest\022\'\n\twf_" +
      "run_id\030\001 \001(\0132\024.littlehorse.WfRunId\0226\n\rev" +
      "ent_def_ids\030\002 \003(\0132\037.littlehorse.Workflow" +
      "EventDefId\022?\n\031workflow_events_to_ignore\030" +
      "\003 \003(\0132\034.littlehorse.WorkflowEventId\"\337\003\n\022" +
      "SearchWfRunRequest\022\025\n\010bookmark\030\001 \001(\014H\000\210\001" +
      "\001\022\022\n\005limit\030\002 \001(\005H\001\210\001\001\022\024\n\014wf_spec_name\030\003 " +
      "\001(\t\022\"\n\025wf_spec_major_version\030\004 \001(\005H\002\210\001\001\022" +
      "\035\n\020wf_spec_revision\030\005 \001(\005H\003\210\001\001\022*\n\006status" +
      "\030\006 \001(\0162\025.littlehorse.LHStatusH\004\210\001\001\0227\n\016ea" +
      "rliest_start\030\007 \001(\0132\032.google.protobuf.Tim" +
      "estampH\005\210\001\001\0225\n\014latest_start\030\010 \001(\0132\032.goog" +
      "le.protobuf.TimestampH\006\210\001\001\0224\n\020variable_f" +
      "ilters\030\t \003(\0132\032.littlehorse.VariableMatch" +
      "B\013\n\t_bookmarkB\010\n\006_limitB\030\n\026_wf_spec_majo" +
      "r_versionB\023\n\021_wf_spec_revisionB\t\n\007_statu" +
      "sB\021\n\017_earliest_startB\017\n\r_latest_start\"X\n" +
      "\013WfRunIdList\022%\n\007results\030\001 \003(\0132\024.littleho" +
      "rse.WfRunId\022\025\n\010bookmark\030\002 \001(\014H\000\210\001\001B\013\n\t_b" +
      "ookmark\"\274\002\n\024SearchTaskRunRequest\022\025\n\010book" +
      "mark\030\001 \001(\014H\000\210\001\001\022\022\n\005limit\030\002 \001(\005H\001\210\001\001\022\025\n\rt" +
      "ask_def_name\030\003 \001(\t\022,\n\006status\030\004 \001(\0162\027.lit" +
      "tlehorse.TaskStatusH\002\210\001\001\0227\n\016earliest_sta" +
      "rt\030\005 \001(\0132\032.google.protobuf.TimestampH\003\210\001" +
      "\001\0225\n\014latest_start\030\006 \001(\0132\032.google.protobu" +
      "f.TimestampH\004\210\001\001B\013\n\t_bookmarkB\010\n\006_limitB" +
      "\t\n\007_statusB\021\n\017_earliest_startB\017\n\r_latest" +
      "_start\"\\\n\rTaskRunIdList\022\'\n\007results\030\001 \003(\013" +
      "2\026.littlehorse.TaskRunId\022\025\n\010bookmark\030\002 \001" +
      "(\014H\000\210\001\001B\013\n\t_bookmark\"\361\003\n\024SearchNodeRunRe" +
      "quest\022\025\n\010bookmark\030\001 \001(\014H\000\210\001\001\022\022\n\005limit\030\002 " +
      "\001(\005H\001\210\001\001\0227\n\016earliest_start\030\003 \001(\0132\032.googl" +
      "e.protobuf.TimestampH\002\210\001\001\0225\n\014latest_star" +
      "t\030\004 \001(\0132\032.google.protobuf.TimestampH\003\210\001\001" +
      "\022=\n\tnode_type\030\005 \001(\0162*.littlehorse.Search" +
      "NodeRunRequest.NodeType\022%\n\006status\030\006 \001(\0162" +
      "\025.littlehorse.LHStatus\"\234\001\n\010NodeType\022\010\n\004T" +
      "ASK\020\000\022\022\n\016EXTERNAL_EVENT\020\001\022\016\n\nENTRYPOINT\020" +
      "\002\022\010\n\004EXIT\020\003\022\020\n\014START_THREAD\020\004\022\020\n\014WAIT_TH" +
      "READS\020\005\022\t\n\005SLEEP\020\006\022\r\n\tUSER_TASK\020\007\022\032\n\026STA" +
      "RT_MULTIPLE_THREADS\020\010B\013\n\t_bookmarkB\010\n\006_l" +
      "imitB\021\n\017_earliest_startB\017\n\r_latest_start" +
      "\"\\\n\rNodeRunIdList\022\'\n\007results\030\001 \003(\0132\026.lit" +
      "tlehorse.NodeRunId\022\025\n\010bookmark\030\002 \001(\014H\000\210\001" +
      "\001B\013\n\t_bookmark\"\262\003\n\030SearchUserTaskRunRequ" +
      "est\022\025\n\010bookmark\030\001 \001(\014H\000\210\001\001\022\022\n\005limit\030\002 \001(" +
      "\005H\001\210\001\001\0223\n\006status\030\003 \001(\0162\036.littlehorse.Use" +
      "rTaskRunStatusH\002\210\001\001\022\037\n\022user_task_def_nam" +
      "e\030\004 \001(\tH\003\210\001\001\022\024\n\007user_id\030\005 \001(\tH\004\210\001\001\022\027\n\nus" +
      "er_group\030\006 \001(\tH\005\210\001\001\0227\n\016earliest_start\030\007 " +
      "\001(\0132\032.google.protobuf.TimestampH\006\210\001\001\0225\n\014" +
      "latest_start\030\010 \001(\0132\032.google.protobuf.Tim" +
      "estampH\007\210\001\001B\013\n\t_bookmarkB\010\n\006_limitB\t\n\007_s" +
      "tatusB\025\n\023_user_task_def_nameB\n\n\010_user_id" +
      "B\r\n\013_user_groupB\021\n\017_earliest_startB\017\n\r_l" +
      "atest_start\"d\n\021UserTaskRunIdList\022+\n\007resu" +
      "lts\030\001 \003(\0132\032.littlehorse.UserTaskRunId\022\025\n" +
      "\010bookmark\030\002 \001(\014H\000\210\001\001B\013\n\t_bookmark\"\236\002\n\025Se" +
      "archVariableRequest\022\025\n\010bookmark\030\001 \001(\014H\000\210" +
      "\001\001\022\022\n\005limit\030\002 \001(\005H\001\210\001\001\022)\n\005value\030\003 \001(\0132\032." +
      "littlehorse.VariableValue\022\"\n\025wf_spec_maj" +
      "or_version\030\004 \001(\005H\002\210\001\001\022\035\n\020wf_spec_revisio" +
      "n\030\005 \001(\005H\003\210\001\001\022\020\n\010var_name\030\006 \001(\t\022\024\n\014wf_spe" +
      "c_name\030\007 \001(\tB\013\n\t_bookmarkB\010\n\006_limitB\030\n\026_" +
      "wf_spec_major_versionB\023\n\021_wf_spec_revisi" +
      "on\"^\n\016VariableIdList\022(\n\007results\030\001 \003(\0132\027." +
      "littlehorse.VariableId\022\025\n\010bookmark\030\002 \001(\014" +
      "H\000\210\001\001B\013\n\t_bookmark\"x\n\024SearchTaskDefReque" +
      "st\022\025\n\010bookmark\030\001 \001(\014H\000\210\001\001\022\022\n\005limit\030\002 \001(\005" +
      "H\001\210\001\001\022\023\n\006prefix\030\003 \001(\tH\002\210\001\001B\013\n\t_bookmarkB" +
      "\010\n\006_limitB\t\n\007_prefix\"\\\n\rTaskDefIdList\022\'\n" +
      "\007results\030\001 \003(\0132\026.littlehorse.TaskDefId\022\025" +
      "\n\010bookmark\030\002 \001(\014H\000\210\001\001B\013\n\t_bookmark\"\230\001\n\030S" +
      "earchUserTaskDefRequest\022\025\n\010bookmark\030\001 \001(" +
      "\014H\001\210\001\001\022\022\n\005limit\030\002 \001(\005H\002\210\001\001\022\020\n\006prefix\030\003 \001" +
      "(\tH\000\022\016\n\004name\030\004 \001(\tH\000B\030\n\026user_task_def_cr" +
      "iteriaB\013\n\t_bookmarkB\010\n\006_limit\"d\n\021UserTas" +
      "kDefIdList\022+\n\007results\030\001 \003(\0132\032.littlehors" +
      "e.UserTaskDefId\022\025\n\010bookmark\030\002 \001(\014H\000\210\001\001B\013" +
      "\n\t_bookmark\"\246\001\n\023SearchWfSpecRequest\022\025\n\010b" +
      "ookmark\030\001 \001(\014H\001\210\001\001\022\022\n\005limit\030\002 \001(\005H\002\210\001\001\022\016" +
      "\n\004name\030\003 \001(\tH\000\022\020\n\006prefix\030\004 \001(\tH\000\022\027\n\rtask" +
      "_def_name\030\005 \001(\tH\000B\022\n\020wf_spec_criteriaB\013\n" +
      "\t_bookmarkB\010\n\006_limit\"Z\n\014WfSpecIdList\022&\n\007" +
      "results\030\001 \003(\0132\025.littlehorse.WfSpecId\022\025\n\010" +
      "bookmark\030\002 \001(\014H\000\210\001\001B\013\n\t_bookmark\"\201\001\n\035Sea" +
      "rchExternalEventDefRequest\022\025\n\010bookmark\030\001" +
      " \001(\014H\000\210\001\001\022\022\n\005limit\030\002 \001(\005H\001\210\001\001\022\023\n\006prefix\030" +
      "\003 \001(\tH\002\210\001\001B\013\n\t_bookmarkB\010\n\006_limitB\t\n\007_pr" +
      "efix\"n\n\026ExternalEventDefIdList\0220\n\007result" +
      "s\030\001 \003(\0132\037.littlehorse.ExternalEventDefId" +
      "\022\025\n\010bookmark\030\002 \001(\014H\000\210\001\001B\013\n\t_bookmark\"W\n\023" +
      "SearchTenantRequest\022\022\n\005limit\030\001 \001(\005H\000\210\001\001\022" +
      "\025\n\010bookmark\030\002 \001(\014H\001\210\001\001B\010\n\006_limitB\013\n\t_boo" +
      "kmark\"Z\n\014TenantIdList\022&\n\007results\030\001 \003(\0132\025" +
      ".littlehorse.TenantId\022\025\n\010bookmark\030\002 \001(\014H" +
      "\000\210\001\001B\013\n\t_bookmark\"\200\003\n\032SearchExternalEven" +
      "tRequest\022\025\n\010bookmark\030\001 \001(\014H\001\210\001\001\022\022\n\005limit" +
      "\030\002 \001(\005H\002\210\001\001\022)\n\twf_run_id\030\003 \001(\0132\024.littleh" +
      "orse.WfRunIdH\000\022u\n\"external_event_def_nam" +
      "e_and_status\030\004 \001(\0132G.littlehorse.SearchE" +
      "xternalEventRequest.ByExtEvtDefNameAndSt" +
      "atusRequestH\000\032j\n\037ByExtEvtDefNameAndStatu" +
      "sRequest\022\037\n\027external_event_def_name\030\001 \001(" +
      "\t\022\027\n\nis_claimed\030\002 \001(\010H\000\210\001\001B\r\n\013_is_claime" +
      "dB\022\n\020ext_evt_criteriaB\013\n\t_bookmarkB\010\n\006_l" +
      "imit\"h\n\023ExternalEventIdList\022-\n\007results\030\001" +
      " \003(\0132\034.littlehorse.ExternalEventId\022\025\n\010bo" +
      "okmark\030\002 \001(\014H\000\210\001\001B\013\n\t_bookmark\">\n\023ListNo" +
      "deRunsRequest\022\'\n\twf_run_id\030\001 \001(\0132\024.littl" +
      "ehorse.WfRunId\"4\n\013NodeRunList\022%\n\007results" +
      "\030\001 \003(\0132\024.littlehorse.NodeRun\"?\n\024ListVari" +
      "ablesRequest\022\'\n\twf_run_id\030\001 \001(\0132\024.little" +
      "horse.WfRunId\"6\n\014VariableList\022&\n\007results" +
      "\030\001 \003(\0132\025.littlehorse.Variable\"D\n\031ListExt" +
      "ernalEventsRequest\022\'\n\twf_run_id\030\001 \001(\0132\024." +
      "littlehorse.WfRunId\"@\n\021ExternalEventList" +
      "\022+\n\007results\030\001 \003(\0132\032.littlehorse.External" +
      "Event\"w\n\031RegisterTaskWorkerRequest\022\026\n\016ta" +
      "sk_worker_id\030\001 \001(\t\022+\n\013task_def_id\030\002 \001(\0132" +
      "\026.littlehorse.TaskDefId\022\025\n\rlistener_name" +
      "\030\003 \001(\t\"s\n\032TaskWorkerHeartBeatRequest\022\021\n\t" +
      "client_id\030\001 \001(\t\022+\n\013task_def_id\030\002 \001(\0132\026.l" +
      "ittlehorse.TaskDefId\022\025\n\rlistener_name\030\003 " +
      "\001(\t\"\201\001\n\032RegisterTaskWorkerResponse\022+\n\nyo" +
      "ur_hosts\030\001 \003(\0132\027.littlehorse.LHHostInfo\022" +
      "\037\n\022is_cluster_healthy\030\002 \001(\010H\000\210\001\001B\025\n\023_is_" +
      "cluster_healthy\"(\n\nLHHostInfo\022\014\n\004host\030\001 " +
      "\001(\t\022\014\n\004port\030\002 \001(\005\"\213\001\n\017PollTaskRequest\022+\n" +
      "\013task_def_id\030\001 \001(\0132\026.littlehorse.TaskDef" +
      "Id\022\021\n\tclient_id\030\002 \001(\t\022 \n\023task_worker_ver" +
      "sion\030\003 \001(\tH\000\210\001\001B\026\n\024_task_worker_version\"" +
      "\214\002\n\rScheduledTask\022+\n\013task_run_id\030\001 \001(\0132\026" +
      ".littlehorse.TaskRunId\022+\n\013task_def_id\030\002 " +
      "\001(\0132\026.littlehorse.TaskDefId\022\026\n\016attempt_n" +
      "umber\030\003 \001(\005\022-\n\tvariables\030\004 \003(\0132\032.littleh" +
      "orse.VarNameAndVal\022.\n\ncreated_at\030\005 \001(\0132\032" +
      ".google.protobuf.Timestamp\022*\n\006source\030\006 \001" +
      "(\0132\032.littlehorse.TaskRunSource\"N\n\020PollTa" +
      "skResponse\022/\n\006result\030\001 \001(\0132\032.littlehorse" +
      ".ScheduledTaskH\000\210\001\001B\t\n\007_result\"\201\003\n\rRepor" +
      "tTaskRun\022+\n\013task_run_id\030\001 \001(\0132\026.littleho" +
      "rse.TaskRunId\022(\n\004time\030\002 \001(\0132\032.google.pro" +
      "tobuf.Timestamp\022\'\n\006status\030\003 \001(\0162\027.little" +
      "horse.TaskStatus\0223\n\nlog_output\030\005 \001(\0132\032.l" +
      "ittlehorse.VariableValueH\001\210\001\001\022\026\n\016attempt" +
      "_number\030\006 \001(\005\022,\n\006output\030\004 \001(\0132\032.littleho" +
      "rse.VariableValueH\000\022)\n\005error\030\007 \001(\0132\030.lit" +
      "tlehorse.LHTaskErrorH\000\0221\n\texception\030\010 \001(" +
      "\0132\034.littlehorse.LHTaskExceptionH\000B\010\n\006res" +
      "ultB\r\n\013_log_output\"V\n\020StopWfRunRequest\022\'" +
      "\n\twf_run_id\030\001 \001(\0132\024.littlehorse.WfRunId\022" +
      "\031\n\021thread_run_number\030\002 \001(\005\"X\n\022ResumeWfRu" +
      "nRequest\022\'\n\twf_run_id\030\001 \001(\0132\024.littlehors" +
      "e.WfRunId\022\031\n\021thread_run_number\030\002 \001(\005\"\263\001\n" +
      "\032TaskDefMetricsQueryRequest\0220\n\014window_st" +
      "art\030\001 \001(\0132\032.google.protobuf.Timestamp\0225\n" +
      "\013window_type\030\002 \001(\0162 .littlehorse.Metrics" +
      "WindowLength\022\032\n\rtask_def_name\030\003 \001(\tH\000\210\001\001" +
      "B\020\n\016_task_def_name\"\312\001\n\026ListTaskMetricsRe" +
      "quest\022+\n\013task_def_id\030\001 \001(\0132\026.littlehorse" +
      ".TaskDefId\0225\n\021last_window_start\030\002 \001(\0132\032." +
      "google.protobuf.Timestamp\0227\n\rwindow_leng" +
      "th\030\003 \001(\0162 .littlehorse.MetricsWindowLeng" +
      "th\022\023\n\013num_windows\030\004 \001(\005\"G\n\027ListTaskMetri" +
      "csResponse\022,\n\007results\030\001 \003(\0132\033.littlehors" +
      "e.TaskDefMetrics\"\261\001\n\031WfSpecMetricsQueryR" +
      "equest\022)\n\nwf_spec_id\030\001 \001(\0132\025.littlehorse" +
      ".WfSpecId\0220\n\014window_start\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\0227\n\rwindow_length\030\003 \001" +
      "(\0162 .littlehorse.MetricsWindowLength\"\306\001\n" +
      "\024ListWfMetricsRequest\022)\n\nwf_spec_id\030\001 \001(" +
      "\0132\025.littlehorse.WfSpecId\0225\n\021last_window_" +
      "start\030\002 \001(\0132\032.google.protobuf.Timestamp\022" +
      "7\n\rwindow_length\030\003 \001(\0162 .littlehorse.Met" +
      "ricsWindowLength\022\023\n\013num_windows\030\004 \001(\005\"D\n" +
      "\025ListWfMetricsResponse\022+\n\007results\030\001 \003(\0132" +
      "\032.littlehorse.WfSpecMetrics\"\373\002\n\016TaskDefM" +
      "etrics\022+\n\013task_def_id\030\001 \001(\0132\026.littlehors" +
      "e.TaskDefId\0220\n\014window_start\030\002 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022.\n\004type\030\003 \001(\0162 .li" +
      "ttlehorse.MetricsWindowLength\022\035\n\025schedul" +
      "e_to_start_max\030\004 \001(\003\022\035\n\025schedule_to_star" +
      "t_avg\030\005 \001(\003\022\035\n\025start_to_complete_max\030\006 \001" +
      "(\003\022\035\n\025start_to_complete_avg\030\007 \001(\003\022\027\n\017tot" +
      "al_completed\030\010 \001(\003\022\025\n\rtotal_errored\030\t \001(" +
      "\003\022\025\n\rtotal_started\030\n \001(\003\022\027\n\017total_schedu" +
      "led\030\013 \001(\003\"\241\002\n\rWfSpecMetrics\022)\n\nwf_spec_i" +
      "d\030\001 \001(\0132\025.littlehorse.WfSpecId\0220\n\014window" +
      "_start\030\002 \001(\0132\032.google.protobuf.Timestamp" +
      "\022.\n\004type\030\003 \001(\0162 .littlehorse.MetricsWind" +
      "owLength\022\025\n\rtotal_started\030\004 \001(\003\022\027\n\017total" +
      "_completed\030\005 \001(\003\022\025\n\rtotal_errored\030\006 \001(\003\022" +
      "\035\n\025start_to_complete_max\030\007 \001(\003\022\035\n\025start_" +
      "to_complete_avg\030\010 \001(\003\"A\n\026ListUserTaskRun" +
      "Request\022\'\n\twf_run_id\030\001 \001(\0132\024.littlehorse" +
      ".WfRunId\"<\n\017UserTaskRunList\022)\n\007results\030\001" +
      " \003(\0132\030.littlehorse.UserTaskRun\">\n\023ListTa" +
      "skRunsRequest\022\'\n\twf_run_id\030\001 \001(\0132\024.littl" +
      "ehorse.WfRunId\"4\n\013TaskRunList\022%\n\007results" +
      "\030\001 \003(\0132\024.littlehorse.TaskRun\"z\n\024MigrateW" +
      "fSpecRequest\022*\n\013old_wf_spec\030\001 \001(\0132\025.litt" +
      "lehorse.WfSpecId\0226\n\tmigration\030\002 \001(\0132#.li" +
      "ttlehorse.WfSpecVersionMigration\"T\n\026GetL" +
      "atestWfSpecRequest\022\014\n\004name\030\001 \001(\t\022\032\n\rmajo" +
      "r_version\030\002 \001(\005H\000\210\001\001B\020\n\016_major_version\"\234" +
      "\001\n\025ServerVersionResponse\022\025\n\rmajor_versio" +
      "n\030\001 \001(\005\022\025\n\rminor_version\030\002 \001(\005\022\025\n\rpatch_" +
      "version\030\003 \001(\005\022#\n\026pre_release_identifier\030" +
      "\004 \001(\tH\000\210\001\001B\031\n\027_pre_release_identifier*P\n" +
      "\021AllowedUpdateType\022\017\n\013ALL_UPDATES\020\000\022\032\n\026M" +
      "INOR_REVISION_UPDATES\020\001\022\016\n\nNO_UPDATES\020\0022" +
      "\300%\n\013LittleHorse\022D\n\nPutTaskDef\022\036.littleho" +
      "rse.PutTaskDefRequest\032\024.littlehorse.Task" +
      "Def\"\000\022<\n\nGetTaskDef\022\026.littlehorse.TaskDe" +
      "fId\032\024.littlehorse.TaskDef\"\000\022_\n\023PutExtern" +
      "alEventDef\022\'.littlehorse.PutExternalEven" +
      "tDefRequest\032\035.littlehorse.ExternalEventD" +
      "ef\"\000\022W\n\023GetExternalEventDef\022\037.littlehors" +
      "e.ExternalEventDefId\032\035.littlehorse.Exter" +
      "nalEventDef\"\000\022_\n\023PutWorkflowEventDef\022\'.l" +
      "ittlehorse.PutWorkflowEventDefRequest\032\035." +
      "littlehorse.WorkflowEventDef\"\000\022A\n\tPutWfS" +
      "pec\022\035.littlehorse.PutWfSpecRequest\032\023.lit" +
      "tlehorse.WfSpec\"\000\0229\n\tGetWfSpec\022\025.littleh" +
      "orse.WfSpecId\032\023.littlehorse.WfSpec\"\000\022M\n\017" +
      "GetLatestWfSpec\022#.littlehorse.GetLatestW" +
      "fSpecRequest\032\023.littlehorse.WfSpec\"\000\022I\n\rM" +
      "igrateWfSpec\022!.littlehorse.MigrateWfSpec" +
      "Request\032\023.littlehorse.WfSpec\"\000\022P\n\016PutUse" +
      "rTaskDef\022\".littlehorse.PutUserTaskDefReq" +
      "uest\032\030.littlehorse.UserTaskDef\"\000\022H\n\016GetU" +
      "serTaskDef\022\032.littlehorse.UserTaskDefId\032\030" +
      ".littlehorse.UserTaskDef\"\000\022\\\n\024GetLatestU" +
      "serTaskDef\022(.littlehorse.GetLatestUserTa" +
      "skDefRequest\032\030.littlehorse.UserTaskDef\"\000" +
      "\0228\n\005RunWf\022\031.littlehorse.RunWfRequest\032\022.l" +
      "ittlehorse.WfRun\"\000\0226\n\010GetWfRun\022\024.littleh" +
      "orse.WfRunId\032\022.littlehorse.WfRun\"\000\022H\n\016Ge" +
      "tUserTaskRun\022\032.littlehorse.UserTaskRunId" +
      "\032\030.littlehorse.UserTaskRun\"\000\022T\n\021AssignUs" +
      "erTaskRun\022%.littlehorse.AssignUserTaskRu" +
      "nRequest\032\026.google.protobuf.Empty\"\000\022X\n\023Co" +
      "mpleteUserTaskRun\022\'.littlehorse.Complete" +
      "UserTaskRunRequest\032\026.google.protobuf.Emp" +
      "ty\"\000\022T\n\021CancelUserTaskRun\022%.littlehorse." +
      "CancelUserTaskRunRequest\032\026.google.protob" +
      "uf.Empty\"\000\022W\n\020ListUserTaskRuns\022#.littleh" +
      "orse.ListUserTaskRunRequest\032\034.littlehors" +
      "e.UserTaskRunList\"\000\022<\n\nGetNodeRun\022\026.litt" +
      "lehorse.NodeRunId\032\024.littlehorse.NodeRun\"" +
      "\000\022L\n\014ListNodeRuns\022 .littlehorse.ListNode" +
      "RunsRequest\032\030.littlehorse.NodeRunList\"\000\022" +
      "<\n\nGetTaskRun\022\026.littlehorse.TaskRunId\032\024." +
      "littlehorse.TaskRun\"\000\022L\n\014ListTaskRuns\022 ." +
      "littlehorse.ListTaskRunsRequest\032\030.little" +
      "horse.TaskRunList\"\000\022?\n\013GetVariable\022\027.lit" +
      "tlehorse.VariableId\032\025.littlehorse.Variab" +
      "le\"\000\022O\n\rListVariables\022!.littlehorse.List" +
      "VariablesRequest\032\031.littlehorse.VariableL" +
      "ist\"\000\022V\n\020PutExternalEvent\022$.littlehorse." +
      "PutExternalEventRequest\032\032.littlehorse.Ex" +
      "ternalEvent\"\000\022N\n\020GetExternalEvent\022\034.litt" +
      "lehorse.ExternalEventId\032\032.littlehorse.Ex" +
      "ternalEvent\"\000\022Z\n\022AwaitWorkflowEvent\022&.li" +
      "ttlehorse.AwaitWorkflowEventRequest\032\032.li" +
      "ttlehorse.WorkflowEvent\"\000\022^\n\022ListExterna" +
      "lEvents\022&.littlehorse.ListExternalEvents" +
      "Request\032\036.littlehorse.ExternalEventList\"" +
      "\000\022J\n\013SearchWfRun\022\037.littlehorse.SearchWfR" +
      "unRequest\032\030.littlehorse.WfRunIdList\"\000\022P\n" +
      "\rSearchNodeRun\022!.littlehorse.SearchNodeR" +
      "unRequest\032\032.littlehorse.NodeRunIdList\"\000\022" +
      "P\n\rSearchTaskRun\022!.littlehorse.SearchTas" +
      "kRunRequest\032\032.littlehorse.TaskRunIdList\"" +
      "\000\022\\\n\021SearchUserTaskRun\022%.littlehorse.Sea" +
      "rchUserTaskRunRequest\032\036.littlehorse.User" +
      "TaskRunIdList\"\000\022S\n\016SearchVariable\022\".litt" +
      "lehorse.SearchVariableRequest\032\033.littleho" +
      "rse.VariableIdList\"\000\022b\n\023SearchExternalEv" +
      "ent\022\'.littlehorse.SearchExternalEventReq" +
      "uest\032 .littlehorse.ExternalEventIdList\"\000" +
      "\022P\n\rSearchTaskDef\022!.littlehorse.SearchTa" +
      "skDefRequest\032\032.littlehorse.TaskDefIdList" +
      "\"\000\022\\\n\021SearchUserTaskDef\022%.littlehorse.Se" +
      "archUserTaskDefRequest\032\036.littlehorse.Use" +
      "rTaskDefIdList\"\000\022M\n\014SearchWfSpec\022 .littl" +
      "ehorse.SearchWfSpecRequest\032\031.littlehorse" +
      ".WfSpecIdList\"\000\022k\n\026SearchExternalEventDe" +
      "f\022*.littlehorse.SearchExternalEventDefRe" +
      "quest\032#.littlehorse.ExternalEventDefIdLi" +
      "st\"\000\022M\n\014SearchTenant\022 .littlehorse.Searc" +
      "hTenantRequest\032\031.littlehorse.TenantIdLis" +
      "t\"\000\022g\n\022RegisterTaskWorker\022&.littlehorse." +
      "RegisterTaskWorkerRequest\032\'.littlehorse." +
      "RegisterTaskWorkerResponse\"\000\022M\n\010PollTask" +
      "\022\034.littlehorse.PollTaskRequest\032\035.littleh" +
      "orse.PollTaskResponse\"\000(\0010\001\022B\n\nReportTas" +
      "k\022\032.littlehorse.ReportTaskRun\032\026.google.p" +
      "rotobuf.Empty\"\000\022D\n\tStopWfRun\022\035.littlehor" +
      "se.StopWfRunRequest\032\026.google.protobuf.Em" +
      "pty\"\000\022H\n\013ResumeWfRun\022\037.littlehorse.Resum" +
      "eWfRunRequest\032\026.google.protobuf.Empty\"\000\022" +
      "H\n\013DeleteWfRun\022\037.littlehorse.DeleteWfRun" +
      "Request\032\026.google.protobuf.Empty\"\000\022L\n\rDel" +
      "eteTaskDef\022!.littlehorse.DeleteTaskDefRe" +
      "quest\032\026.google.protobuf.Empty\"\000\022J\n\014Delet" +
      "eWfSpec\022 .littlehorse.DeleteWfSpecReques" +
      "t\032\026.google.protobuf.Empty\"\000\022T\n\021DeleteUse" +
      "rTaskDef\022%.littlehorse.DeleteUserTaskDef" +
      "Request\032\026.google.protobuf.Empty\"\000\022^\n\026Del" +
      "eteExternalEventDef\022*.littlehorse.Delete" +
      "ExternalEventDefRequest\032\026.google.protobu" +
      "f.Empty\"\000\022a\n\027GetTaskDefMetricsWindow\022\'.l" +
      "ittlehorse.TaskDefMetricsQueryRequest\032\033." +
      "littlehorse.TaskDefMetrics\"\000\022^\n\026GetWfSpe" +
      "cMetricsWindow\022&.littlehorse.WfSpecMetri" +
      "csQueryRequest\032\032.littlehorse.WfSpecMetri" +
      "cs\"\000\022a\n\022ListTaskDefMetrics\022#.littlehorse" +
      ".ListTaskMetricsRequest\032$.littlehorse.Li" +
      "stTaskMetricsResponse\"\000\022\\\n\021ListWfSpecMet" +
      "rics\022!.littlehorse.ListWfMetricsRequest\032" +
      "\".littlehorse.ListWfMetricsResponse\"\000\022A\n" +
      "\tPutTenant\022\035.littlehorse.PutTenantReques" +
      "t\032\023.littlehorse.Tenant\"\000\022J\n\014PutPrincipal" +
      "\022 .littlehorse.PutPrincipalRequest\032\026.lit" +
      "tlehorse.Principal\"\000\022:\n\006Whoami\022\026.google." +
      "protobuf.Empty\032\026.littlehorse.Principal\"\000" +
      "\022P\n\020GetServerVersion\022\026.google.protobuf.E" +
      "mpty\032\".littlehorse.ServerVersionResponse" +
      "\"\000\022N\n\014EnableMetric\022 .littlehorse.EnableM" +
      "etricRequest\032\032.littlehorse.MonitorConfig" +
      "\"\000BG\n\037io.littlehorse.sdk.common.protoP\001Z" +
      "\007.;model\252\002\030LittleHorse.Common.Protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          io.littlehorse.sdk.common.proto.CommonWfspec.getDescriptor(),
          io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor(),
          io.littlehorse.sdk.common.proto.ObjectId.getDescriptor(),
          io.littlehorse.sdk.common.proto.VariableOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.ExternalEventOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.WfRunOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.NodeRunOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.TaskRunOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.UserTasks.getDescriptor(),
          io.littlehorse.sdk.common.proto.WfSpecOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.TaskDefOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.Acls.getDescriptor(),
          io.littlehorse.sdk.common.proto.WorkflowEventOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.Metrics.getDescriptor(),
        });
    internal_static_littlehorse_GetLatestUserTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_littlehorse_GetLatestUserTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_GetLatestUserTaskDefRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_littlehorse_PutWfSpecRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_littlehorse_PutWfSpecRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutWfSpecRequest_descriptor,
        new java.lang.String[] { "Name", "ThreadSpecs", "EntrypointThreadName", "RetentionPolicy", "ParentWfSpec", "AllowedUpdates", "RetentionPolicy", "ParentWfSpec", });
    internal_static_littlehorse_PutWfSpecRequest_ThreadSpecsEntry_descriptor =
      internal_static_littlehorse_PutWfSpecRequest_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_PutWfSpecRequest_ThreadSpecsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutWfSpecRequest_ThreadSpecsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_PutTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_littlehorse_PutTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutTaskDefRequest_descriptor,
        new java.lang.String[] { "Name", "InputVars", });
    internal_static_littlehorse_PutWorkflowEventDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_littlehorse_PutWorkflowEventDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutWorkflowEventDefRequest_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_littlehorse_PutUserTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_littlehorse_PutUserTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutUserTaskDefRequest_descriptor,
        new java.lang.String[] { "Name", "Fields", "Description", "Description", });
    internal_static_littlehorse_PutExternalEventDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_littlehorse_PutExternalEventDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutExternalEventDefRequest_descriptor,
        new java.lang.String[] { "Name", "RetentionPolicy", });
    internal_static_littlehorse_PutExternalEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_littlehorse_PutExternalEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PutExternalEventRequest_descriptor,
        new java.lang.String[] { "WfRunId", "ExternalEventDefId", "Guid", "Content", "ThreadRunNumber", "NodeRunPosition", "Guid", "ThreadRunNumber", "NodeRunPosition", });
    internal_static_littlehorse_DeleteExternalEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_littlehorse_DeleteExternalEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteExternalEventRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_DeleteWfRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_littlehorse_DeleteWfRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteWfRunRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_DeleteTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_littlehorse_DeleteTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteTaskDefRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_DeleteUserTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_littlehorse_DeleteUserTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteUserTaskDefRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_DeleteWfSpecRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_littlehorse_DeleteWfSpecRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteWfSpecRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_DeleteExternalEventDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_littlehorse_DeleteExternalEventDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteExternalEventDefRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_littlehorse_RunWfRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_littlehorse_RunWfRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_RunWfRequest_descriptor,
        new java.lang.String[] { "WfSpecName", "MajorVersion", "Revision", "Variables", "Id", "ParentWfRunId", "MajorVersion", "Revision", "Id", "ParentWfRunId", });
    internal_static_littlehorse_RunWfRequest_VariablesEntry_descriptor =
      internal_static_littlehorse_RunWfRequest_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_RunWfRequest_VariablesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_RunWfRequest_VariablesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_VariableMatch_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_littlehorse_VariableMatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableMatch_descriptor,
        new java.lang.String[] { "VarName", "Value", });
    internal_static_littlehorse_AwaitWorkflowEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_littlehorse_AwaitWorkflowEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_AwaitWorkflowEventRequest_descriptor,
        new java.lang.String[] { "WfRunId", "EventDefIds", "WorkflowEventsToIgnore", });
    internal_static_littlehorse_SearchWfRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_littlehorse_SearchWfRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchWfRunRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "WfSpecName", "WfSpecMajorVersion", "WfSpecRevision", "Status", "EarliestStart", "LatestStart", "VariableFilters", "Bookmark", "Limit", "WfSpecMajorVersion", "WfSpecRevision", "Status", "EarliestStart", "LatestStart", });
    internal_static_littlehorse_WfRunIdList_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_littlehorse_WfRunIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_WfRunIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchTaskRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_littlehorse_SearchTaskRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchTaskRunRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "TaskDefName", "Status", "EarliestStart", "LatestStart", "Bookmark", "Limit", "Status", "EarliestStart", "LatestStart", });
    internal_static_littlehorse_TaskRunIdList_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_littlehorse_TaskRunIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskRunIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchNodeRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_littlehorse_SearchNodeRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchNodeRunRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "EarliestStart", "LatestStart", "NodeType", "Status", "Bookmark", "Limit", "EarliestStart", "LatestStart", });
    internal_static_littlehorse_NodeRunIdList_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_littlehorse_NodeRunIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_NodeRunIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchUserTaskRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_littlehorse_SearchUserTaskRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchUserTaskRunRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "Status", "UserTaskDefName", "UserId", "UserGroup", "EarliestStart", "LatestStart", "Bookmark", "Limit", "Status", "UserTaskDefName", "UserId", "UserGroup", "EarliestStart", "LatestStart", });
    internal_static_littlehorse_UserTaskRunIdList_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_littlehorse_UserTaskRunIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskRunIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchVariableRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_littlehorse_SearchVariableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchVariableRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "Value", "WfSpecMajorVersion", "WfSpecRevision", "VarName", "WfSpecName", "Bookmark", "Limit", "WfSpecMajorVersion", "WfSpecRevision", });
    internal_static_littlehorse_VariableIdList_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_littlehorse_VariableIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_littlehorse_SearchTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchTaskDefRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "Prefix", "Bookmark", "Limit", "Prefix", });
    internal_static_littlehorse_TaskDefIdList_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_littlehorse_TaskDefIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskDefIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchUserTaskDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_littlehorse_SearchUserTaskDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchUserTaskDefRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "Prefix", "Name", "UserTaskDefCriteria", "Bookmark", "Limit", });
    internal_static_littlehorse_UserTaskDefIdList_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_littlehorse_UserTaskDefIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskDefIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchWfSpecRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_littlehorse_SearchWfSpecRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchWfSpecRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "Name", "Prefix", "TaskDefName", "WfSpecCriteria", "Bookmark", "Limit", });
    internal_static_littlehorse_WfSpecIdList_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_littlehorse_WfSpecIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_WfSpecIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchExternalEventDefRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_littlehorse_SearchExternalEventDefRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchExternalEventDefRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "Prefix", "Bookmark", "Limit", "Prefix", });
    internal_static_littlehorse_ExternalEventDefIdList_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_littlehorse_ExternalEventDefIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ExternalEventDefIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchTenantRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_littlehorse_SearchTenantRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchTenantRequest_descriptor,
        new java.lang.String[] { "Limit", "Bookmark", "Limit", "Bookmark", });
    internal_static_littlehorse_TenantIdList_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_littlehorse_TenantIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TenantIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_SearchExternalEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_littlehorse_SearchExternalEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchExternalEventRequest_descriptor,
        new java.lang.String[] { "Bookmark", "Limit", "WfRunId", "ExternalEventDefNameAndStatus", "ExtEvtCriteria", "Bookmark", "Limit", });
    internal_static_littlehorse_SearchExternalEventRequest_ByExtEvtDefNameAndStatusRequest_descriptor =
      internal_static_littlehorse_SearchExternalEventRequest_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_SearchExternalEventRequest_ByExtEvtDefNameAndStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SearchExternalEventRequest_ByExtEvtDefNameAndStatusRequest_descriptor,
        new java.lang.String[] { "ExternalEventDefName", "IsClaimed", "IsClaimed", });
    internal_static_littlehorse_ExternalEventIdList_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_littlehorse_ExternalEventIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ExternalEventIdList_descriptor,
        new java.lang.String[] { "Results", "Bookmark", "Bookmark", });
    internal_static_littlehorse_ListNodeRunsRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_littlehorse_ListNodeRunsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListNodeRunsRequest_descriptor,
        new java.lang.String[] { "WfRunId", });
    internal_static_littlehorse_NodeRunList_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_littlehorse_NodeRunList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_NodeRunList_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_ListVariablesRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_littlehorse_ListVariablesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListVariablesRequest_descriptor,
        new java.lang.String[] { "WfRunId", });
    internal_static_littlehorse_VariableList_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_littlehorse_VariableList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableList_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_ListExternalEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_littlehorse_ListExternalEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListExternalEventsRequest_descriptor,
        new java.lang.String[] { "WfRunId", });
    internal_static_littlehorse_ExternalEventList_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_littlehorse_ExternalEventList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ExternalEventList_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_RegisterTaskWorkerRequest_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_littlehorse_RegisterTaskWorkerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_RegisterTaskWorkerRequest_descriptor,
        new java.lang.String[] { "TaskWorkerId", "TaskDefId", "ListenerName", });
    internal_static_littlehorse_TaskWorkerHeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_littlehorse_TaskWorkerHeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskWorkerHeartBeatRequest_descriptor,
        new java.lang.String[] { "ClientId", "TaskDefId", "ListenerName", });
    internal_static_littlehorse_RegisterTaskWorkerResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_littlehorse_RegisterTaskWorkerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_RegisterTaskWorkerResponse_descriptor,
        new java.lang.String[] { "YourHosts", "IsClusterHealthy", "IsClusterHealthy", });
    internal_static_littlehorse_LHHostInfo_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_littlehorse_LHHostInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_LHHostInfo_descriptor,
        new java.lang.String[] { "Host", "Port", });
    internal_static_littlehorse_PollTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_littlehorse_PollTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PollTaskRequest_descriptor,
        new java.lang.String[] { "TaskDefId", "ClientId", "TaskWorkerVersion", "TaskWorkerVersion", });
    internal_static_littlehorse_ScheduledTask_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_littlehorse_ScheduledTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ScheduledTask_descriptor,
        new java.lang.String[] { "TaskRunId", "TaskDefId", "AttemptNumber", "Variables", "CreatedAt", "Source", });
    internal_static_littlehorse_PollTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_littlehorse_PollTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_PollTaskResponse_descriptor,
        new java.lang.String[] { "Result", "Result", });
    internal_static_littlehorse_ReportTaskRun_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_littlehorse_ReportTaskRun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ReportTaskRun_descriptor,
        new java.lang.String[] { "TaskRunId", "Time", "Status", "LogOutput", "AttemptNumber", "Output", "Error", "Exception", "Result", "LogOutput", });
    internal_static_littlehorse_StopWfRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_littlehorse_StopWfRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_StopWfRunRequest_descriptor,
        new java.lang.String[] { "WfRunId", "ThreadRunNumber", });
    internal_static_littlehorse_ResumeWfRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_littlehorse_ResumeWfRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ResumeWfRunRequest_descriptor,
        new java.lang.String[] { "WfRunId", "ThreadRunNumber", });
    internal_static_littlehorse_TaskDefMetricsQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_littlehorse_TaskDefMetricsQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskDefMetricsQueryRequest_descriptor,
        new java.lang.String[] { "WindowStart", "WindowType", "TaskDefName", "TaskDefName", });
    internal_static_littlehorse_ListTaskMetricsRequest_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_littlehorse_ListTaskMetricsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListTaskMetricsRequest_descriptor,
        new java.lang.String[] { "TaskDefId", "LastWindowStart", "WindowLength", "NumWindows", });
    internal_static_littlehorse_ListTaskMetricsResponse_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_littlehorse_ListTaskMetricsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListTaskMetricsResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_WfSpecMetricsQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_littlehorse_WfSpecMetricsQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_WfSpecMetricsQueryRequest_descriptor,
        new java.lang.String[] { "WfSpecId", "WindowStart", "WindowLength", });
    internal_static_littlehorse_ListWfMetricsRequest_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_littlehorse_ListWfMetricsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListWfMetricsRequest_descriptor,
        new java.lang.String[] { "WfSpecId", "LastWindowStart", "WindowLength", "NumWindows", });
    internal_static_littlehorse_ListWfMetricsResponse_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_littlehorse_ListWfMetricsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListWfMetricsResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_TaskDefMetrics_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_littlehorse_TaskDefMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskDefMetrics_descriptor,
        new java.lang.String[] { "TaskDefId", "WindowStart", "Type", "ScheduleToStartMax", "ScheduleToStartAvg", "StartToCompleteMax", "StartToCompleteAvg", "TotalCompleted", "TotalErrored", "TotalStarted", "TotalScheduled", });
    internal_static_littlehorse_WfSpecMetrics_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_littlehorse_WfSpecMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_WfSpecMetrics_descriptor,
        new java.lang.String[] { "WfSpecId", "WindowStart", "Type", "TotalStarted", "TotalCompleted", "TotalErrored", "StartToCompleteMax", "StartToCompleteAvg", });
    internal_static_littlehorse_ListUserTaskRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_littlehorse_ListUserTaskRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListUserTaskRunRequest_descriptor,
        new java.lang.String[] { "WfRunId", });
    internal_static_littlehorse_UserTaskRunList_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_littlehorse_UserTaskRunList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskRunList_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_ListTaskRunsRequest_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_littlehorse_ListTaskRunsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ListTaskRunsRequest_descriptor,
        new java.lang.String[] { "WfRunId", });
    internal_static_littlehorse_TaskRunList_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_littlehorse_TaskRunList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskRunList_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_littlehorse_MigrateWfSpecRequest_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_littlehorse_MigrateWfSpecRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_MigrateWfSpecRequest_descriptor,
        new java.lang.String[] { "OldWfSpec", "Migration", });
    internal_static_littlehorse_GetLatestWfSpecRequest_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_littlehorse_GetLatestWfSpecRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_GetLatestWfSpecRequest_descriptor,
        new java.lang.String[] { "Name", "MajorVersion", "MajorVersion", });
    internal_static_littlehorse_ServerVersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_littlehorse_ServerVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ServerVersionResponse_descriptor,
        new java.lang.String[] { "MajorVersion", "MinorVersion", "PatchVersion", "PreReleaseIdentifier", "PreReleaseIdentifier", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    io.littlehorse.sdk.common.proto.CommonWfspec.getDescriptor();
    io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor();
    io.littlehorse.sdk.common.proto.ObjectId.getDescriptor();
    io.littlehorse.sdk.common.proto.VariableOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.ExternalEventOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.WfRunOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.NodeRunOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.TaskRunOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.UserTasks.getDescriptor();
    io.littlehorse.sdk.common.proto.WfSpecOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.TaskDefOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.Acls.getDescriptor();
    io.littlehorse.sdk.common.proto.WorkflowEventOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.Metrics.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
