// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package io.littlehorse.sdk.common.proto;

public interface UsageMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.UsageMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int64 value = 2;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <code>.google.protobuf.Timestamp window_start = 3;</code>
   * @return Whether the windowStart field is set.
   */
  boolean hasWindowStart();
  /**
   * <code>.google.protobuf.Timestamp window_start = 3;</code>
   * @return The windowStart.
   */
  com.google.protobuf.Timestamp getWindowStart();
  /**
   * <code>.google.protobuf.Timestamp window_start = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp window_end = 4;</code>
   * @return Whether the windowEnd field is set.
   */
  boolean hasWindowEnd();
  /**
   * <code>.google.protobuf.Timestamp window_end = 4;</code>
   * @return The windowEnd.
   */
  com.google.protobuf.Timestamp getWindowEnd();
  /**
   * <code>.google.protobuf.Timestamp window_end = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder();
}
